/**
 * Generated by scripts/fleet-measure.mjs — do not edit.
 *
 * Every number here is counted from the fleet's source. The prose, the groups
 * and the flows are authored in graph.ts; these are the measurements those
 * buildings are sized by.
 */

export type Measured = { count: number; loc: number }

export const MEASURED: Record<string, Measured> = {
  "admission-console": { count: 1, loc: 304 },
  "admission-desk": { count: 16, loc: 12657 },
  "admission-email": { count: 1, loc: 559 },
  "admission-ledger": { count: 8, loc: 10587 },
  "agent-studio-service": { count: 47, loc: 10086 },
  "agent-studio-ui": { count: 53, loc: 10544 },
  "chat-rollout": { count: 15, loc: 5346 },
  "chat-sandbox": { count: 13, loc: 3578 },
  "doorway-agent": { count: 4, loc: 4739 },
  "doorway-classes": { count: 2, loc: 1150 },
  "doorway-front": { count: 21, loc: 7740 },
  "doorway-signin": { count: 2, loc: 701 },
  "gateway-auth": { count: 1, loc: 511 },
  "gateway-endpoint": { count: 35, loc: 10958 },
  "gateway-upstream": { count: 2, loc: 2110 },
  "identity-library": { count: 6, loc: 1758 },
  "model-access-api": { count: 5, loc: 2095 },
  "model-access-registry": { count: 7, loc: 2895 },
  "sandbox-service": { count: 14, loc: 4057 },
  "site-studio-service": { count: 71, loc: 17692 },
  "site-studio-ui": { count: 65, loc: 11913 },
}

/** Source files no node claims. Above zero means the map is behind the code. */
export const UNCLAIMED: readonly string[] = [

]

export const TOTALS = { repos: 9, files: 389, loc: 121980 } as const
