#!/usr/bin/env node
/**
 * Measure the fleet, so the skyline is derived rather than typed.
 *
 * The architecture-map skill ships a sync script that measures one repository
 * against one coverage table. This map spans nine, so the same idea is applied
 * one scale up: every node claims files in a named repo, every source file in
 * every repo must be claimed exactly once, and what nothing claims is drift.
 *
 * Repos are read from working copies beside this one (FLEET_SRC_ROOT, default
 * `..`). A repo that is missing is reported, not silently skipped — a zero that
 * looks like a measurement is worse than a gap that announces itself.
 *
 * `--check` exits non-zero when the committed numbers no longer match, which is
 * what keeps a confident-looking map from quietly going stale.
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const SRC_ROOT = resolve(ROOT, process.env.FLEET_SRC_ROOT ?? '..')
const OUTPUT = join(ROOT, 'src/architecture/measured.generated.ts')

const config = JSON.parse(readFileSync(join(ROOT, 'fleet.config.json'), 'utf8'))
const coverage = JSON.parse(readFileSync(join(ROOT, 'coverage.json'), 'utf8'))
const check = process.argv.includes('--check')

/** Minimal glob → RegExp: `**` crosses directories, `*` does not. */
function globToRegExp(glob) {
  let out = '^'
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i]
    if (c === '*') {
      if (glob[i + 1] === '*') {
        out += '.*'
        i++
        if (glob[i + 1] === '/') i++
      } else out += '[^/]*'
    } else if (c === '.') out += '\\.'
    else if (c === '?') out += '[^/]'
    else if ('+^${}()|[]\\'.includes(c)) out += `\\${c}`
    else out += c
  }
  return new RegExp(`${out}$`)
}

const matchers = new Map()
function matches(path, patterns) {
  return patterns.some((pattern) => {
    let re = matchers.get(pattern)
    if (re === undefined) {
      re = globToRegExp(pattern)
      matchers.set(pattern, re)
    }
    return re.test(path)
  })
}

const REF = process.env.FLEET_REF ?? 'origin/main'

/**
 * Tracked files on the measured ref — not whatever is lying in a working copy.
 *
 * The first version of this walked the filesystem and reported 958,000 lines,
 * because it had faithfully counted `.next` build caches, a Python venv and two
 * directories of git worktrees. Reading the ref instead means the map measures
 * the fleet as it is committed, and a dirty checkout cannot move a building.
 */
function trackedFiles(repoDir) {
  const out = execFileSync('git', ['-C', repoDir, 'ls-tree', '-r', '--name-only', REF], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  return out.split('\n').filter((line) => line.length > 0)
}

function countLines(repoDir, file) {
  try {
    const text = execFileSync('git', ['-C', repoDir, 'show', `${REF}:${file}`], {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    })
    if (text.length === 0) return 0
    let lines = 0
    for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) lines++
    return text.endsWith('\n') ? lines : lines + 1
  } catch {
    return 0
  }
}

/* Claims: node id → [{ repo, paths, priority }] */
const claims = []
for (const [nodeId, entry] of Object.entries(coverage)) {
  if (nodeId.startsWith('$')) continue
  for (const claim of Array.isArray(entry) ? entry : [entry]) {
    claims.push({
      nodeId,
      repo: claim.repo,
      paths: claim.paths ?? ['**'],
      priority: claim.priority ?? 0,
    })
  }
}
claims.sort((a, b) => b.priority - a.priority)

const measures = new Map()
const unmapped = []
const missingRepos = []

for (const repo of config.repos) {
  const repoDir = join(SRC_ROOT, repo)
  if (!existsSync(repoDir) || !statSync(repoDir).isDirectory()) {
    missingRepos.push(repo)
    continue
  }
  for (const file of trackedFiles(repoDir)) {
    if (!matches(file, config.sources)) continue
    if (matches(file, config.ignore)) continue
    const claim = claims.find((c) => c.repo === repo && matches(file, c.paths))
    if (claim === undefined) {
      unmapped.push(`${repo}/${file}`)
      continue
    }
    const current = measures.get(claim.nodeId) ?? { count: 0, loc: 0 }
    current.count += 1
    current.loc += countLines(repoDir, file)
    measures.set(claim.nodeId, current)
  }
}

for (const { nodeId } of claims) if (!measures.has(nodeId)) measures.set(nodeId, { count: 0, loc: 0 })

const sortedMeasures = [...measures.entries()].sort(([a], [b]) => a.localeCompare(b))
const totalFiles = sortedMeasures.reduce((sum, [, m]) => sum + m.count, 0)
const totalLoc = sortedMeasures.reduce((sum, [, m]) => sum + m.loc, 0)

const body = `/**
 * Generated by scripts/fleet-measure.mjs — do not edit.
 *
 * Every number here is counted from the fleet's source. The prose, the groups
 * and the flows are authored in graph.ts; these are the measurements those
 * buildings are sized by.
 */

export type Measured = { count: number; loc: number }

export const MEASURED: Record<string, Measured> = {
${sortedMeasures.map(([id, m]) => `  ${JSON.stringify(id)}: { count: ${m.count}, loc: ${m.loc} },`).join('\n')}
}

/** Source files no node claims. Above zero means the map is behind the code. */
export const UNCLAIMED: readonly string[] = [
${unmapped.sort().map((f) => `  ${JSON.stringify(f)},`).join('\n')}
]

export const TOTALS = { repos: ${config.repos.length}, files: ${totalFiles}, loc: ${totalLoc} } as const
`

if (missingRepos.length > 0) {
  console.error(`Missing working copies under ${SRC_ROOT}: ${missingRepos.join(', ')}`)
  console.error('Clone them beside this repo, or set FLEET_SRC_ROOT.')
  process.exit(1)
}

if (check) {
  const existing = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : ''
  if (existing !== body) {
    console.error('Fleet measurements are stale. Run `bun run measure` and commit the result.')
    process.exit(1)
  }
  console.log(`Fleet measurements current: ${totalFiles} files, ${totalLoc} lines, ${unmapped.length} unmapped.`)
  process.exit(0)
}

writeFileSync(OUTPUT, body)
console.log(`Measured ${config.repos.length} repos: ${totalFiles} files, ${totalLoc} lines.`)
console.log(unmapped.length === 0 ? 'Every source file is claimed.' : `${unmapped.length} unmapped files:`)
for (const file of unmapped.slice(0, 40)) console.log(`  ${file}`)
if (unmapped.length > 40) console.log(`  … and ${unmapped.length - 40} more`)
